package ProjectJava;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import ProjectJava.DBConnectionNV;
import ProjectJava.nhanvien;
import ProjectJava.Main;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author FPT
 */
public class DangNhap extends javax.swing.JFrame {
    private Main main;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DangNhap.class.getName());

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        buttonGroup1.add(rdoAdmin);
        buttonGroup1.add(rdoStaff);
        ButtonGroup bg = new ButtonGroup();
        bg.add(rdoAdmin);
        bg.add(rdoStaff);
        rdoStaff.setSelected(true);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelleft = new javax.swing.JPanel();
        lblWELCOME = new javax.swing.JLabel();
        lblTO = new javax.swing.JLabel();
        lblDRSHOP = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        panelright = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoStaff = new javax.swing.JRadioButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập Hệ Thống");

        panelleft.setBackground(new java.awt.Color(255, 153, 102));

        lblWELCOME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWELCOME.setForeground(new java.awt.Color(255, 255, 255));
        lblWELCOME.setText("WELCOME");

        lblTO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTO.setForeground(new java.awt.Color(255, 255, 255));
        lblTO.setText("TO");

        lblDRSHOP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDRSHOP.setForeground(new java.awt.Color(255, 255, 255));
        lblDRSHOP.setText("DRINK SHOP");


        lbLogo.setText("LOGO");

        javax.swing.GroupLayout panelleftLayout = new javax.swing.GroupLayout(panelleft);
        panelleft.setLayout(panelleftLayout);
        panelleftLayout.setHorizontalGroup(
            panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelleftLayout.createSequentialGroup()
                .addGroup(panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblWELCOME, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelleftLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblTO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelleftLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblDRSHOP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelleftLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelleftLayout.setVerticalGroup(
            panelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelleftLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbLogo)
                .addGap(29, 29, 29)
                .addComponent(lblWELCOME, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTO)
                .addGap(26, 26, 26)
                .addComponent(lblDRSHOP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("[ ĐĂNG NHẬP HỆ THỐNG ]");

        lblEmail.setText("Email:");

        lblPass.setText("Mật khẩu:");

        btnLogin.setText("Đăng nhập");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        rdoAdmin.setText("Admin");
        rdoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAdminActionPerformed(evt);
            }
        });

        rdoStaff.setText("Nhân viên");
        rdoStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelrightLayout = new javax.swing.GroupLayout(panelright);
        panelright.setLayout(panelrightLayout);
        panelrightLayout.setHorizontalGroup(
            panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelrightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(46, 46, 46))
            .addGroup(panelrightLayout.createSequentialGroup()
                .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelrightLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(panelrightLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rdoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(rdoStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelrightLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelrightLayout.setVerticalGroup(
            panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrightLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoStaff)
                    .addComponent(rdoAdmin))
                .addGap(26, 26, 26)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelleft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

    String username = txtEmail.getText().trim();
    String password = txtPassword.getText().trim();
    String role = " ";

    if (rdoAdmin.isSelected()) role = "admin";
    else if (rdoStaff.isSelected()) role = "staff";

    if (username.isEmpty() || password.isEmpty() || role.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        return;
    }
    nhanvien nv = DBConnectionNV.checkLogin(username, password);

    if(nv != null){
        String roleDB = nv.getRole().trim();
        if (rdoAdmin.isSelected()) {
                if (!roleDB.equalsIgnoreCase("admin")) {
                    JOptionPane.showMessageDialog(this, 
                        "Tài khoản này là Nhân viên, vui lòng chọn mục 'Nhân viên'!", 
                        "Sai vai trò", JOptionPane.WARNING_MESSAGE);
                    return; // Chặn lại, không cho vào
                }
            }
            
            // Trường hợp 2: Người dùng tích chọn NHÂN VIÊN
        if (rdoStaff.isSelected()) {
                // Kiểm tra xem trong DB có phải là 'admin' không. Nếu là admin mà chọn staff thì báo lỗi
                // Hoặc kiểm tra xem roleDB có phải là 'staff' hoặc 'NhanVien' không
                if (roleDB.equalsIgnoreCase("admin")) {
                    JOptionPane.showMessageDialog(this, 
                        "Tài khoản này là Admin, vui lòng chọn mục 'Admin'!", 
                        "Sai vai trò", JOptionPane.WARNING_MESSAGE);
                    return; // Chặn lại
                }
        }

        Session.email = nv.getEmail();
        Session.role = nv.getRole();
        Session.userId = nv.getID_employee();
        JOptionPane.showMessageDialog(this, "Đăng nhập thành công!\nXin chào: " + nv.getName_employee());
        new Main(nv).setVisible(true);
        this.dispose();
    }else{
        JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu!\", \"Lỗi\", JOptionPane.ERROR_MESSAGE ");
    }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void rdoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAdminActionPerformed

    private void rdoStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new DangNhap().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lblDRSHOP;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTO;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWELCOME;
    private javax.swing.JPanel panelleft;
    private javax.swing.JPanel panelright;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
